apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: basic-rollout
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: basic-rollout
  endpoints:
    - port: http
      path: /metrics
