apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vanilla-blue-green
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: vanilla-blue-green
  endpoints:
    - port: http
      path: /metrics
